### ISSUE TITLE
[Q] Execution crashes on multiple `Decref` calls (?)

### ISSUE THREAD

**Issue by Ngiong** [google/re2#341]
Hi.
I found that unintentional multiple calls to `Decref` cause the program to crash, as shown in the following code snippet.
I'm actually not sure whether this could cause vulnerability (or not), and whether the re2 library should prevent such cases.

```c++
#include "re2/re2.h"
#include "re2/regexp.h"

int main() {
  re2::Regexp::ParseFlags parseflags22 = re2::Regexp::ParseFlags::OneLine;
  re2::Regexp* regexp23 = re2::Regexp::NewLiteral(0, parseflags22);
  re2::Regexp* regexp24 = re2::Regexp::Plus(regexp23, parseflags22);
  regexp24->Decref();
  regexp24->Decref();
  re2::RE2 re28{"plplnj7J"}; // crash (?)
}
```

This is the gdb backtrace information we obtained from running the above snippet.
```
#0  tcache_get (tc_idx=<optimized out>) at malloc.c:2937
#1  __GI___libc_malloc (bytes=40) at malloc.c:3051
#2  0x00007f97255deb39 in operator new(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000055b488bbd3f5 in re2::Regexp::ParseState::PushLiteral (this=0x7ffe009625c0, r=112) at re2/parse.cc:420
#4  0x000055b488bc2eca in re2::Regexp::Parse (s=..., global_flags=re2::Regexp::LikePerl, status=0x7ffe00962660) at re2/parse.cc:2238
#5  0x000055b488b7c942 in re2::RE2::Init (this=0x7ffe009628f0, pattern=..., options=...) at re2/re2.cc:199
#6  0x000055b488b7c163 in re2::RE2::RE2 (this=0x7ffe009628f0, pattern=0x55b488bd800a "plplnj7J") at re2/re2.cc:114
#7  0x000055b488b7bddc in main () at re2/playground.cpp:10
#8  0x00007f972534e0b3 in __libc_start_main (main=0x55b488b7bd49 <main()>, argc=1, argv=0x7ffe00962ac8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe00962ab8) at ../csu/libc-start.c:308
#9  0x000055b488b7bc8e in _start ()
```

Thank you.

**Comment by junyer** [comment]
The first call to `Decref()` frees `regexp24`. The second call to `Decref()` uses `regexp24` after it was freed, which invokes undefined behaviour. You can presumably verify this by running the code under ASan.
