### ISSUE TITLE
AttributeError: partially initialized module 're2' has no attribute 'search' (most likely due to a circular import)

### ISSUE THREAD

**Issue by atsaloli** [google/re2#414]
Hello. 

I just tried using re2 from Python and I got the error `AttributeError: partially initialized module 're2' has no attribute 'search' (most likely due to a circular import)`:

```
[:~] [my-venv] 1 $ cat /tmp/re2.py
import re2
re2.search (".*", "hello")
[:~] [my-venv] $ python /tmp/re2.py
Traceback (most recent call last):
  File "/tmp/re2.py", line 1, in <module>
    import re2
  File "/tmp/re2.py", line 2, in <module>
    re2.search (".*", "hello")
    ^^^^^^^^^^
AttributeError: partially initialized module 're2' has no attribute 'search' (most likely due to a circular import)
[:~] [my-venv] 1 $ python -V
Python 3.11.2
[:~] [my-venv] $ pip freeze | grep re2
google-re2==1.0
[:~] [my-venv] $ dpkg -l | grep libre2 | grep eff
ii  libre2-9:amd64                       20210201+dfsg-1                   amd64        efficient, principled regular expression library
ii  libre2-dev:amd64                     20210201+dfsg-1                   amd64        efficient, principled regular expression library, development kit
[:~] [my-venv] $ lsb_release -sd
Debian GNU/Linux 11 (bullseye)
[:~] [my-venv] $
```
Am I using the module wrong?

**Comment by junyer** [comment]
My best guess is that Python gets confused because your script is named `re2.py`. What happens if you rename your script?

**Comment by atsaloli** [comment]
That was it! Thank you! 

```
[:~] [my-venv] $ mv /tmp/re2.py /tmp/test.py
[:~] [my-venv] $ python /tmp/test.py
[:~] [my-venv] $
```
